### ISSUE TITLE
adding images

### ISSUE THREAD

**Issue by tharrington** [rsanchezsaez/CardboardSDK-iOS#1]
Hi - looks like a cool project. I downloaded it and ran it on my phone. I was wondering, how would I use images in this? is there anyway I can just pass images in and simply move my phone around?

**Comment by rsanchezsaez** [comment]
Hi,

that would be a matter of using OpenGL to display textures in the appropriate parts of the 3D space. If you are not familiar with OpenGL, I suggest you start [here](https://open.gl/introduction).
