### ISSUE TITLE
Undefined symbols for architecture armv7:   "_CTFontGetGlyphsForCharacters" ...  in libGoogleKitCore.a(GoogleKitCore.o)

### ISSUE THREAD

**Issue by Fygo** [rsanchezsaez/CardboardSDK-iOS#11]
Hi there,

I tried your SDK a month or so ago, it was working very nicely.
However, recently I updated the Cardboard SDK in my project (I think it was like a week ago) and now I cannot compile it for iOS, even tho I follow the same steps - the ones you wrote. Every time I want to compile, I get the following errors:

Undefined symbols for architecture armv7:
  "_CTFontGetGlyphsForCharacters", referenced from:
      l302 in libGoogleKitCore.a(GoogleKitCore.o)
  "_CTFontCreateWithName", referenced from:
      l299 in libGoogleKitCore.a(GoogleKitCore.o)
  "_CTFontManagerRegisterFontsForURL", referenced from:
      l231 in libGoogleKitCore.a(GoogleKitCore.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is a screenshot:
![error](https://cloud.githubusercontent.com/assets/5912274/8040696/101c9d82-0dd8-11e5-9777-0a364c6e03d9.png)
Any ideas what can be causing this? Thanks a lot!

**Comment by rsanchezsaez** [comment]
Are you trying to use the Unity part? If that's the case I suggest you look at Google's official Unity plugin, as they have added iOS support recently.

**Comment by Fygo** [comment]
@rsanchezsaez Sorry for the late reply and you are totally right, works out of the box now, excellent! Thank you.
