### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by raptox** [rsanchezsaez/CardboardSDK-iOS#12]
Hello there,

writing it in Swift 2 would be cool.

I am currently using it for a project. Maybe I could help?

regards

**Comment by rsanchezsaez** [comment]
Hi @raptox, sorry for my late reply. It's quite easy to import and use _Objective-C_ libraries on _Swift_ projects.

I don't see any immediate benefit in rewriting the inner SDK in _Swift_, but it'd be great to have an additional example (e.g., `CGDTreasure`) written in _Swift_.

I'm closing this issue now, but if you had any _Swift_ example code that you want to contribute, please feel free to submit a PR. (Try to model its structure within the project as a sibling to `CBDTreasure`, with its own separate project file.) :-)
