### ISSUE TITLE
Use CardboardSDK-iOS with equirectangular images

### ISSUE THREAD

**Issue by SafouaneAzzabi** [rsanchezsaez/CardboardSDK-iOS#14]
Hi
How can I show a GLKView in a cardboard mode?
Thanks

**Comment by rsanchezsaez** [comment]
Hi,

I suggest you look at how the `TextOverlayView : CGDStereoGLView` class is used in `TreasureViewController` on the `CBDTreasure` example to display UI.

Probably, you don't want to add an additional `GLKView`, but you may want to instead directly draw the _OpenGL_ content on the `GLKView` that's already supplied by `CBDViewController` through the `drawEyeWithEye:` method.

Closing this issue now, feel free to open a new one if you have any additional questions.
