### ISSUE TITLE
How could I add a sphere inside the virtual world?

### ISSUE THREAD

**Issue by tomtomtong** [rsanchezsaez/CardboardSDK-iOS#25]
I would like to add a photosphere image and map it to a sphere. Are there any example codes for this?
Thx.

**Comment by rsanchezsaez** [comment]
Hey @tomtomtong 

I'm afraid I don't have specific example code on how to map a photosphere photo onto a sphere.

In case it helps, we have recently merged a _SceneKit+SpriteKit example_ onto the main repository, look for the `CBDSceneKit` example project. Maybe you can use _SceneKit_ and _SpriteKit_ to map textures into spheres with relative ease. Look for example into this [SO question](http://stackoverflow.com/questions/35023170/add-shape-to-sphere-surface-in-scenekit), which is not exactly what you're looking for, but may point you in the right direction.
