### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by yalong5837** [rsanchezsaez/CardboardSDK-iOS#28]
**\* Assertion failure in -[GCSSphericalMetadataExtractor intFromBytes:withLength:], googlemac/iPhone/CardboardSDK/Source/GCSSphericalMetadataExtractor.mm:201

**Comment by rsanchezsaez** [comment]
I think your problem is with the official Google VR SDK, not with this unofficial version. Please report it there: https://github.com/googlevr/gvr-ios-sdk
