### ISSUE TITLE
Build error: __unity_getFrameParameters

### ISSUE THREAD

**Issue by ashleydb** [rsanchezsaez/CardboardSDK-iOS#5]
Hi,
I'm trying to build this with Unity 5.0.1f1 and Xcode 6.3 for iPhone 5S on iOS 8.3.
I followed your steps for setting up the project. Version A wouldn't work, (the Append option was greyed out,) so I went with option B and built to a new folder and added the resources you mention. However, I get a build error I can't resolve:

```
Undefined symbols for architecture armv7:
  "__unity_getFrameParameters", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I see `_unity_getFrameParameters` in CardboardUnity.cpp, so I'm not sure what the issue is. Any hints?
Thanks
Ash

**Comment by rsanchezsaez** [comment]
Did you follow step 4 on your _Unity_ generated _Xcode_ project? Make sure all the CardboardSDK `.m` and `.mm` sources files are part of your project target in _Xcode_.

![screen-shot-2015-04-20-at-12 27 44](https://cloud.githubusercontent.com/assets/444313/7229249/86ff9080-e759-11e4-8fd2-29c148b06c35.png)

**Comment by ashleydb** [comment]
Yes sir. Here are screenshots of steps 4, 5 & 6.

FWIW, I only see the Target Membership setting on the CardboardSDK folder, not each file under it.

![step4](https://cloud.githubusercontent.com/assets/11968457/7245494/fc7f45f2-e7a0-11e4-9ba3-f980a43adfa2.png)
![step5](https://cloud.githubusercontent.com/assets/11968457/7245496/fe48b422-e7a0-11e4-9b72-dc662e08ac05.png)
![step6](https://cloud.githubusercontent.com/assets/11968457/7245497/006cce82-e7a1-11e4-8631-568e1226ab5f.png)

**Comment by ashleydb** [comment]
Ah, I figured it out. Needed to select Group instead of Folder Reference in step 4. Thanks for the pointer.

![step4](https://cloud.githubusercontent.com/assets/11968457/7245682/7003c8c4-e7a4-11e4-926d-40a288089415.png)

**Comment by rsanchezsaez** [comment]
Great! Cheers.

**Comment by rsanchezsaez** [comment]
If you happen to do any improvements on the Unity side, please feel free to contribute them back. Noticeably: we are missing magnetic trigger support from Unity right now. I think it shouldn't be too difficult to implement.

**Comment by stefkeB** [comment]
I had to replace all occurrences of ".x" ".y" and ".z" with ".v[0]" ".v[1]" and ".v[2]" respectively. It seems that the GLVector3 that was begin used, only generated the v array and not the xyz, rgb and others.
